// d3.tip
// Copyright (c) 2013 Justin Palmer
//
// Tooltips for d3.js SVG visualizations
d3.tip=function(){function d(a){a=a.node();m="svg"==a.tagName.toLowerCase()?a:a.ownerSVGElement;b=m.createSVGPoint();document.body.appendChild(c)}function e(){var a=d3.event.target,c={},d=a.getScreenCTM(),a=a.getBBox(),e=a.width,f=a.height,g=a.y,h=document.documentElement.scrollTop||document.body.scrollTop;b.x=a.x+(document.documentElement.scrollLeft||document.body.scrollLeft);b.y=g+h;c.nw=b.matrixTransform(d);b.x+=e;c.ne=b.matrixTransform(d);b.y+=f;c.se=b.matrixTransform(d);b.x-=e;c.sw=b.matrixTransform(d);
b.y-=f/2;c.w=b.matrixTransform(d);b.x+=e;c.e=b.matrixTransform(d);b.x-=e/2;b.y-=f/2;c.n=b.matrixTransform(d);b.y+=f;c.s=b.matrixTransform(d);return c}var g=function(){return"n"},h=function(){return[0,0]},l=function(){return" "},c=function(){var a=d3.select(document.createElement("div"));a.style({position:"absolute",opacity:0,pointerEvents:"none",boxSizing:"border-box"});return a.node()}(),m=null,b=null;d.show=function(){var a=l.apply(this,arguments),b=h.apply(this,arguments),e=g.apply(this,arguments),
k=d3.select(c),f=0;for(k.html(a).style({opacity:1,"pointer-events":"all"});f--;)k.classed(p[f],!1);a=n.get(e).apply(this);k.classed(e,!0).style({top:a.top+b[0]+"px",left:a.left+b[1]+"px"});return d};d.hide=function(){nodel=d3.select(c);nodel.style({opacity:0,"pointer-events":"none"});return d};d.attr=function(a,b){if(2>arguments.length&&"string"===typeof a)return d3.select(c).attr(a);var e=Array.prototype.slice.call(arguments);d3.selection.prototype.attr.apply(d3.select(c),e);return d};d.style=function(a,
b){if(2>arguments.length&&"string"===typeof a)return d3.select(c).style(a);var e=Array.prototype.slice.call(arguments);d3.selection.prototype.style.apply(d3.select(c),e);return d};d.direction=function(a){if(!arguments.length)return g;g=null==a?a:d3.functor(a);return d};d.offset=function(a){if(!arguments.length)return h;h=null==a?a:d3.functor(a);return d};d.html=function(a){if(!arguments.length)return l;l=null==a?a:d3.functor(a);return d};var n=d3.map({n:function(){var a=e();return{top:a.n.y-c.offsetHeight,
left:a.n.x-c.offsetWidth/2}},s:function(){var a=e();return{top:a.s.y,left:a.s.x-c.offsetWidth/2}},e:function(){var a=e();return{top:a.e.y-c.offsetHeight/2,left:a.e.x}},w:function(){var a=e();return{top:a.w.y-c.offsetHeight/2,left:a.w.x-c.offsetWidth}},nw:function(){var a=e();return{top:a.nw.y-c.offsetHeight,left:a.nw.x-c.offsetWidth}},ne:function(){var a=e();return{top:a.ne.y-c.offsetHeight,left:a.ne.x}},sw:function(){var a=e();return{top:a.sw.y,left:a.sw.x-c.offsetWidth}},se:function(){var a=e();
return{top:a.se.y,left:a.e.x}}}),p=n.keys();return d};